apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kgl336zqg-go 
  janus-idp.io/tekton: kgl336zqg-go
  backstage.io/kubernetes-id: kgl336zqg-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kgl336zqg-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml