apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kgl336zqg-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kgl336zqg-go 
  name: kgl336zqg-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kgl336zqg-go 
